use glam::Vec3;

use super::{SoundstageConfig, SoundstageLayout};
use crate::camera::{CameraBookmark, CameraNavigationConfig, ThirdPersonConfig};
use crate::scene::{CloudProfile, CloudResolution, SceneSettings};

fn stage_layout() -> SoundstageLayout {
    SoundstageLayout {
        ground_radius: 1800.0,
        ground_thickness: 7.5,
        shadow_depth: 420.0,
    }
}

fn camera_navigation() -> CameraNavigationConfig {
    CameraNavigationConfig {
        min_pitch: -0.65,
        max_pitch: 1.15,
        min_height: 2.5,
        max_height: 82.0,
        roam_center: Vec3::new(0.0, 11.0, 0.0),
        roam_radius: 118.0,
        base_move_speed: 24.0,
        sprint_multiplier: 2.4,
        mouse_sensitivity: 0.010,
        wheel_dolly_speed: 7.0,
    }
}

pub fn hero() -> SoundstageConfig {
    SoundstageConfig {
        scene_settings: SceneSettings {
            sun_direction: Vec3::new(-0.60, 0.38, -0.40).normalize(),
            sun_color: Vec3::new(1.00, 0.93, 0.78),
            sun_strength: 1.35,
            sun_angular_radius: 0.0052,
            fog_density: 0.0020,
            fog_height_falloff: 0.032,
            fog_start: 80.0,
            fog_end: 600.0,
            fog_color: Vec3::new(0.52, 0.60, 0.82),
            fog_sky_mix: 0.02,
            sky_zenith: Vec3::new(0.18, 0.42, 1.80),
            sky_horizon: Vec3::new(0.42, 0.56, 0.96),
            sky_strength: 1.60,
            rayleigh_strength: 1.45,
            mie_strength: 0.36,
            mie_anisotropy: 0.78,
            horizon_haze: 0.42,
            shaft_intensity: 0.35,
            shaft_decay: 0.92,
            ambient_up: Vec3::ZERO,
            ambient_down: Vec3::ZERO,
            ambient_right: Vec3::ZERO,
            ambient_left: Vec3::ZERO,
            ambient_front: Vec3::ZERO,
            ambient_back: Vec3::ZERO,
            exposure: 1.02,
            tonemap_strength: 1.0,
            wind: crate::scene::WindSettings::default(),
            contact_shadow_strength: 0.18,
            ambient_intensity: 1.08,
            gi_intensity: 0.0,
            cloud_coverage: 0.62,
            cloud_profile: CloudProfile {
                coverage: 0.62,
                density_scale: 28.0,
                cloud_base_km: 1.0,
                cloud_top_km: 5.0,
                detail_erosion: 0.55,
                wind_speed: 0.4,
                march_steps: 64,
                light_steps: 8,
                temporal_blend: 0.90,
                resolution: CloudResolution::Quarter,
            },
            fog_volume_density: 0.02,
            fog_volume_albedo: Vec3::new(0.9, 0.9, 0.95),
            fog_volume_anisotropy: 0.3,
            focus_distance: 10.0,
            aperture: 0.01,
            dof_enabled: false,
            motion_blur_enabled: false,
            fxaa_enabled: false,
            area_lights: Vec::new(),
            ca_strength: 0.0,
            film_grain_strength: 0.0,
        },
        layout: stage_layout(),
        camera_bookmark: CameraBookmark {
            position: Vec3::new(65.0, 18.0, 48.0),
            yaw: 0.57 + std::f32::consts::PI,
            pitch: 0.04,
            fov_y_degrees: 48.0,
        },
        camera_navigation: camera_navigation(),
        third_person: ThirdPersonConfig::default(),
        clear_color: [0.18, 0.32, 0.58, 1.0],
    }
}

pub fn low_angle() -> SoundstageConfig {
    SoundstageConfig {
        scene_settings: SceneSettings {
            sun_direction: Vec3::new(-0.58, 0.62, 0.32).normalize(),
            sun_color: Vec3::new(1.00, 0.95, 0.84),
            sun_strength: 1.18,
            sun_angular_radius: 0.0100,
            fog_density: 0.0012,
            fog_height_falloff: 0.10,
            fog_start: 140.0,
            fog_end: 860.0,
            fog_color: Vec3::new(0.40, 0.52, 0.78),
            fog_sky_mix: 0.01,
            sky_zenith: Vec3::new(0.10, 0.23, 1.40),
            sky_horizon: Vec3::new(0.30, 0.46, 0.84),
            sky_strength: 0.98,
            rayleigh_strength: 1.00,
            mie_strength: 0.12,
            mie_anisotropy: 0.78,
            horizon_haze: 0.15,
            shaft_intensity: 0.14,
            shaft_decay: 0.95,
            ambient_up: Vec3::ZERO,
            ambient_down: Vec3::ZERO,
            ambient_right: Vec3::ZERO,
            ambient_left: Vec3::ZERO,
            ambient_front: Vec3::ZERO,
            ambient_back: Vec3::ZERO,
            exposure: 1.04,
            tonemap_strength: 1.0,
            wind: crate::scene::WindSettings::default(),
            contact_shadow_strength: 0.16,
            ambient_intensity: 0.98,
            gi_intensity: 0.0,
            cloud_coverage: 0.30,
            cloud_profile: CloudProfile {
                coverage: 0.30,
                density_scale: 20.0,
                cloud_base_km: 1.2,
                cloud_top_km: 3.6,
                detail_erosion: 0.70,
                wind_speed: 0.9,
                march_steps: 48,
                light_steps: 8,
                temporal_blend: 0.88,
                resolution: CloudResolution::Quarter,
            },
            fog_volume_density: 0.02,
            fog_volume_albedo: Vec3::new(0.9, 0.9, 0.95),
            fog_volume_anisotropy: 0.3,
            focus_distance: 10.0,
            aperture: 0.01,
            dof_enabled: false,
            motion_blur_enabled: false,
            fxaa_enabled: false,
            area_lights: Vec::new(),
            ca_strength: 0.0,
            film_grain_strength: 0.0,
        },
        layout: stage_layout(),
        camera_bookmark: CameraBookmark {
            position: Vec3::new(22.0, 2.0, -16.0),
            yaw: -0.50 + std::f32::consts::PI,
            pitch: -0.18,
            fov_y_degrees: 34.0,
        },
        camera_navigation: camera_navigation(),
        third_person: ThirdPersonConfig::default(),
        clear_color: [0.16, 0.30, 0.54, 1.0],
    }
}

pub fn silhouette() -> SoundstageConfig {
    SoundstageConfig {
        scene_settings: SceneSettings {
            sun_direction: Vec3::new(-0.56, 0.60, -0.28).normalize(),
            sun_color: Vec3::new(1.00, 0.93, 0.82),
            sun_strength: 1.14,
            sun_angular_radius: 0.0100,
            fog_density: 0.0015,
            fog_height_falloff: 0.11,
            fog_start: 120.0,
            fog_end: 740.0,
            fog_color: Vec3::new(0.40, 0.50, 0.74),
            fog_sky_mix: 0.00,
            sky_zenith: Vec3::new(0.09, 0.22, 1.32),
            sky_horizon: Vec3::new(0.28, 0.44, 0.82),
            sky_strength: 0.80,
            rayleigh_strength: 0.96,
            mie_strength: 0.16,
            mie_anisotropy: 0.79,
            horizon_haze: 0.28,
            shaft_intensity: 0.12,
            shaft_decay: 0.94,
            ambient_up: Vec3::ZERO,
            ambient_down: Vec3::ZERO,
            ambient_right: Vec3::ZERO,
            ambient_left: Vec3::ZERO,
            ambient_front: Vec3::ZERO,
            ambient_back: Vec3::ZERO,
            exposure: 0.96,
            tonemap_strength: 1.0,
            wind: crate::scene::WindSettings::default(),
            contact_shadow_strength: 0.15,
            ambient_intensity: 0.90,
            gi_intensity: 0.0,
            cloud_coverage: 0.50,
            cloud_profile: CloudProfile {
                coverage: 0.50,
                density_scale: 18.0,
                cloud_base_km: 1.4,
                cloud_top_km: 3.2,
                detail_erosion: 0.80,
                wind_speed: 0.5,
                march_steps: 48,
                light_steps: 8,
                temporal_blend: 0.88,
                resolution: CloudResolution::Quarter,
            },
            fog_volume_density: 0.02,
            fog_volume_albedo: Vec3::new(0.9, 0.9, 0.95),
            fog_volume_anisotropy: 0.3,
            focus_distance: 10.0,
            aperture: 0.01,
            dof_enabled: false,
            motion_blur_enabled: false,
            fxaa_enabled: false,
            area_lights: Vec::new(),
            ca_strength: 0.0,
            film_grain_strength: 0.0,
        },
        layout: stage_layout(),
        camera_bookmark: CameraBookmark {
            position: Vec3::new(18.0, 4.0, 28.0),
            yaw: 1.08 + std::f32::consts::PI,
            pitch: -0.05,
            fov_y_degrees: 34.0,
        },
        camera_navigation: camera_navigation(),
        third_person: ThirdPersonConfig::default(),
        clear_color: [0.14, 0.26, 0.48, 1.0],
    }
}

pub fn neutral_debug() -> SoundstageConfig {
    SoundstageConfig {
        scene_settings: SceneSettings {
            sun_direction: Vec3::new(-0.42, 0.60, -0.50).normalize(),
            sun_color: Vec3::splat(1.0),
            sun_strength: 1.00,
            sun_angular_radius: 0.0098,
            fog_density: 0.0018,
            fog_height_falloff: 0.08,
            fog_start: 100.0,
            fog_end: 620.0,
            fog_color: Vec3::new(0.38, 0.52, 0.88),
            fog_sky_mix: 0.02,
            sky_zenith: Vec3::new(0.08, 0.20, 1.34),
            sky_horizon: Vec3::new(0.26, 0.44, 0.96),
            sky_strength: 0.74,
            rayleigh_strength: 0.94,
            mie_strength: 0.12,
            mie_anisotropy: 0.70,
            horizon_haze: 0.28,
            shaft_intensity: 0.08,
            shaft_decay: 0.96,
            ambient_up: Vec3::ZERO,
            ambient_down: Vec3::ZERO,
            ambient_right: Vec3::ZERO,
            ambient_left: Vec3::ZERO,
            ambient_front: Vec3::ZERO,
            ambient_back: Vec3::ZERO,
            exposure: 0.98,
            tonemap_strength: 0.88,
            wind: crate::scene::WindSettings::default(),
            contact_shadow_strength: 0.08,
            ambient_intensity: 1.0,
            gi_intensity: 0.0,
            cloud_coverage: 0.38,
            cloud_profile: CloudProfile {
                coverage: 0.38,
                density_scale: 18.0,
                cloud_base_km: 1.8,
                cloud_top_km: 3.4,
                detail_erosion: 0.70,
                wind_speed: 1.0,
                march_steps: 32,
                light_steps: 8,
                temporal_blend: 0.88,
                resolution: CloudResolution::Quarter,
            },
            fog_volume_density: 0.02,
            fog_volume_albedo: Vec3::new(0.9, 0.9, 0.95),
            fog_volume_anisotropy: 0.3,
            focus_distance: 10.0,
            aperture: 0.01,
            dof_enabled: false,
            motion_blur_enabled: false,
            fxaa_enabled: false,
            area_lights: Vec::new(),
            ca_strength: 0.0,
            film_grain_strength: 0.0,
        },
        layout: stage_layout(),
        camera_bookmark: CameraBookmark {
            position: Vec3::new(20.0, 5.0, 22.0),
            yaw: 0.82 + std::f32::consts::PI,
            pitch: -0.05,
            fov_y_degrees: 36.0,
        },
        camera_navigation: camera_navigation(),
        third_person: ThirdPersonConfig::default(),
        clear_color: [0.34, 0.42, 0.55, 1.0],
    }
}
